openapi: 3.0.0
info:
  title: Miro-like Without Api
  description: API from Miro
  version: 1.0.0
paths:
  /boards:
    get:
      $ref: "./endpoints/boards.yaml#/getAllBoards"
    
    post:
      $ref: "./endpoints/boards.yaml#/createBoard"
  
  /boards/{boardId}:
    delete:
      $ref: "./endpoints/boards.yaml#/deleteBoard"